### ISSUE TITLE
Publish Parquet files under an static endpoint

### ISSUE THREAD

**Issue by davidgasquez** [davidgasquez/gitcoin-grants-data-portal#5]
We're putting Parquet files on IPFS. Every release will be under different a IPFS hash and that is both confusing and hard to navigate from the UX side. 

Will aim to rely on [Filebase](https://filebase.com/) and offer an static IPNS endpoint for the exported Parquet files.

**Comment by DistributedDoge** [comment]
Having static endpoint for latest data is a great idea! Just two notes here:

1) When trying to download any of files published using Filebase gateway which is linked on Github Pages [link](https://ipfs.filebase.io/ipns/k51qzi5uqu5dhn3p5xdkp8n6azd4l1mma5zujinkeewhvuh5oq4qvt7etk9tvc/) I am being served `This gateway only serves content pinned by Filebase` string instead of file contents.  

Simple workaround for me is to fetch the same content from another gateway like [cloudflare-gateway](https://cloudflare-ipfs.com/ipns/k51qzi5uqu5dhn3p5xdkp8n6azd4l1mma5zujinkeewhvuh5oq4qvt7etk9tvc/) but I am just curious why Filebase does not seem to recognize they are the ones pinning.

2. In previous version I really enjoyed simplicitly of being able to download single `.duckdb` file with pre-loaded tables. Now I am able to cherry-pick tables and load those myself, but a way to get everything in single fetch with batteries included would be nice.

**Comment by davidgasquez** [comment]
> but I am just curious why Filebase does not seem to recognize they are the ones pinning

Sounds like a bug! IPNS is tricky. Will reach out to Filebase and let them know. Meanwhile, we can rely on the [IPFS CID file](https://github.com/davidgasquez/gitcoin-grants-data-portal/blob/main/data/IPFS_CID).

> In previous version I really enjoyed simplicitly of being able to download single .duckdb file with pre-loaded tables. Now I am able to cherry-pick tables and load those myself, but a way to get everything in single fetch with batteries included would be nice.

You're right! In fact, it doesn't cost much to also push the duckdb database to GitHub releases as I was doing. Might be helpful for (1) people that want one file with everything and (2) as a backup in case IPFS is slow or the CID breaks for some reason.

**Comment by davidgasquez** [comment]
Closing this one as the Parquet files are now being pushed to IPFS. 

Will work on https://github.com/davidgasquez/gitcoin-grants-data-portal/issues/8.
